name: Build and Deploy React App

on:
  push:
    branches:
      - main  # trigger when code is pushed to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install dependencies and build the React app
      - name: Install and Build
        run: |
          npm ci
          npm run build

      # Step 4: Deploy built files to your private server
      - name: Deploy to Server via SSH
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          REMOTE_HOST: 10.1.14.147
          REMOTE_USER: root
          TARGET: /var/www/myapp
          SOURCE: build/
